type state = {
  [key: number]: string;
}

export const processState: state = {
  0: "[NOT INITIALIZED]",
  1: "[IP ASSIGNED]",
  2: "[WAITING OBJECT DETECTION]",
  3: "[TURNING ON MOTOR]", 
  4: "[READING IR CAM SENSOR]",
  5: "[TURNING OFF MOTOR]",
  6: "[TURNING ON LEDS]",
  7: "[TAKING PHOTO]",
  8: "[ANALYZING PHOTO WITH DEEPLEARNING]",
  9: "[TURNING ON MOTOR2]",
  10: "[READING SUITABLE MATERIAL SENSOR]",
  11: "[TURNING OFF MOTOR2]",
  12: "[ACTIVATING SUITABLE SERVO MOTOR]",
  13: "[CLASIFFICATION COMPLETED]",
};
